#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.

APP_NAME="Gradle"
APP_HOME="$(cd "$(dirname "$0")" && pwd -P)"

# Add default JVM options here.
DEFAULT_JVM_OPTS=''

set -e

JAVA_EXE=$(which java)
if [ -z "$JAVA_EXE" ]; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    exit 1
fi

"$JAVA_EXE" -version > /dev/null 2>&1 || {
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    exit 1
}

cd "$APP_HOME"
exec "$JAVA_EXE" $DEFAULT_JVM_OPTS -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
